# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Nickname', models.CharField(max_length=50)),
                ('Phone_no', models.IntegerField(default=0)),
                ('Email', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
