# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TD', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
    ]
