# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD', '0003_remove_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
